name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
    
    - name: Restart Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          cd /root/Discord-Botten/Dikubot
          git pull
          git submodule update --init --recursive
          systemctl stop kuliv.service
          rm -rf ./bin/Release/net7.0
          dotnet publish --configuration Release
          rm -rf ./bin/Release/net7.0/wwwroot
          cp -r Webapp/wwwroot/ ./bin/Release/net7.0
          systemctl start kuliv.service
